"""Generate deterministic gzip payloads and representation-specific cache tags."""
import gzip
import hashlib
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
assets = {
    "html": root / "main/web_ui/dashboard.html",
    "js": root / "main/web_ui/dashboard.js",
    "css": root / "main/web_ui/dashboard.css",
    "burn_graph_js": root / "main/web_ui/burn-graph.js",
    "uplot_js": root / "main/web_ui/vendor/uplot.min.js",
    "uplot_css": root / "main/web_ui/vendor/uplot.min.css",
    "alpine_js": root.parent / "components/captive_portal/alpine.min.js",
    **{name.replace("-", "_"): root / f"main/web_ui/fonts/{name}.woff2"
       for name in ("caprasimo-400", "figtree-400", "figtree-600", "figtree-700")},
}
lines = ["// Generated by tools/generate_web_assets.py; do not edit.", "#pragma once"]
for name, path in assets.items():
    raw = path.read_bytes()
    lines.append(f'#define ASSET_{name}_ETAG "\\\"{hashlib.sha256(raw).hexdigest()[:24]}\\\""')
    if path.suffix != ".woff2":
        compressed = gzip.compress(raw, compresslevel=9, mtime=0)
        lines.append(f'#define ASSET_{name}_GZIP_ETAG "\\\"{hashlib.sha256(compressed).hexdigest()[:24]}\\\""')
        lines.append(f"static const unsigned char asset_{name}_gzip[] = {{")
        for offset in range(0, len(compressed), 20):
            lines.append(",".join(str(b) for b in compressed[offset:offset + 20]) + ",")
        lines.append("};")
output = Path(sys.argv[1])
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines) + "\n")
